# Generated by Django 4.2.28 on 2026-02-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contentblock_caption_alter_post_excerpt_and_more'),
        ('blog', '0002_post_view_count'),
    ]

    operations = [
    ]
